/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package FrontEnd;

import BackEnd.Main;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author potz
 */
public class VisualizarTienda extends javax.swing.JFrame {

    /**
     * Creates new form VisualizarTienda
     */
    public VisualizarTienda() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.pack();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tiendatable = new javax.swing.JTable();
        codigotxt = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        telefono = new javax.swing.JTextField();
        horario = new javax.swing.JTextField();
        nombre = new javax.swing.JTextField();
        direccion = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        codigotexto = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        telefono2 = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        correo2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Visualizar Tienda");
        addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                formComponentShown(evt);
            }
        });

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Ubuntu", 1, 21)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(51, 51, 51));
        jLabel10.setText("Visualizar Tienda:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 20, -1, -1));

        tiendatable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tiendatable);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 130, 780, 120));

        codigotxt.setBackground(new java.awt.Color(153, 153, 153));
        codigotxt.setForeground(new java.awt.Color(51, 51, 51));
        codigotxt.setBorder(null);
        jPanel1.add(codigotxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 90, 180, 30));

        jLabel15.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(51, 51, 51));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Codigo.png"))); // NOI18N
        jPanel1.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, -1, 30));

        jLabel16.setBackground(new java.awt.Color(153, 153, 153));
        jLabel16.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setOpaque(true);
        jPanel1.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 90, 30, 30));

        jLabel7.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Telefono:");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 380, 70, 30));

        jLabel8.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Filtrar Por Codigo-Nombre");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 60, -1, -1));

        jLabel9.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(51, 51, 51));
        jLabel9.setText("Horario:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 340, 60, 30));

        jLabel11.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Nombre:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 300, 70, 30));

        telefono.setEditable(false);
        telefono.setBackground(new java.awt.Color(153, 153, 153));
        telefono.setForeground(new java.awt.Color(51, 51, 51));
        telefono.setBorder(null);
        jPanel1.add(telefono, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 380, 180, 30));

        horario.setEditable(false);
        horario.setBackground(new java.awt.Color(153, 153, 153));
        horario.setForeground(new java.awt.Color(51, 51, 51));
        horario.setBorder(null);
        jPanel1.add(horario, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, 180, 30));

        nombre.setEditable(false);
        nombre.setBackground(new java.awt.Color(153, 153, 153));
        nombre.setForeground(new java.awt.Color(51, 51, 51));
        nombre.setBorder(null);
        jPanel1.add(nombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 180, 30));

        direccion.setEditable(false);
        direccion.setBackground(new java.awt.Color(153, 153, 153));
        direccion.setForeground(new java.awt.Color(51, 51, 51));
        direccion.setBorder(null);
        jPanel1.add(direccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, 180, 30));

        jLabel12.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Direccion:");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 80, 30));

        jLabel13.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(51, 51, 51));
        jLabel13.setText("Codigo:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 60, 30));

        codigotexto.setEditable(false);
        codigotexto.setBackground(new java.awt.Color(153, 153, 153));
        codigotexto.setForeground(new java.awt.Color(51, 51, 51));
        codigotexto.setBorder(null);
        codigotexto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                codigotextoActionPerformed(evt);
            }
        });
        jPanel1.add(codigotexto, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 260, 180, 30));

        jLabel14.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Telefono 2:");
        jPanel1.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 260, 90, 30));

        telefono2.setEditable(false);
        telefono2.setBackground(new java.awt.Color(153, 153, 153));
        telefono2.setForeground(new java.awt.Color(51, 51, 51));
        telefono2.setBorder(null);
        jPanel1.add(telefono2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 260, 180, 30));

        jLabel17.setFont(new java.awt.Font("Ubuntu", 1, 15)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(51, 51, 51));
        jLabel17.setText("Correo:");
        jPanel1.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, 60, 30));

        correo2.setEditable(false);
        correo2.setBackground(new java.awt.Color(153, 153, 153));
        correo2.setForeground(new java.awt.Color(51, 51, 51));
        correo2.setBorder(null);
        jPanel1.add(correo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, 180, 30));

        jButton1.setBackground(new java.awt.Color(153, 153, 153));
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Descripcion.png"))); // NOI18N
        jButton1.setText("Ver TIenda");
        jButton1.setBorder(null);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 380, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/FondoVisualizarTienda.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 860, 420));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_formComponentShown
        llenarTabla(codigotxt, "SELECT * FROM TIENDA ", true, tiendatable, "codigo", "");
        Keilstener();
    }//GEN-LAST:event_formComponentShown

    private void codigotextoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_codigotextoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_codigotextoActionPerformed

    /**
     * Cargamos los datos de la tienda seleccionada y los pasamos a jtextfield para poder visualizarla
     * @param evt 
     */
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int filaselected = tiendatable.getSelectedRow();
        if (filaselected >= 0) {
            String[] datos = new String[7];
            try {
                datos[0] = tiendatable.getValueAt(filaselected, 0).toString();
                datos[1] = tiendatable.getValueAt(filaselected, 1).toString();
                datos[2] = tiendatable.getValueAt(filaselected, 2).toString();
                datos[3] = tiendatable.getValueAt(filaselected, 3).toString();
                datos[4] = tiendatable.getValueAt(filaselected, 4).toString();
                datos[5] = tiendatable.getValueAt(filaselected, 5).toString();
                datos[6] = tiendatable.getValueAt(filaselected, 6).toString();
                codigotexto.setText(datos[0]);
                nombre.setText(datos[1]);
                direccion.setText(datos[2]);
                telefono.setText(datos[3]);
                telefono2.setText(datos[4]);
                correo2.setText(datos[5]);
                horario.setText(datos[6]);
            } catch (Exception e) {
            }
            
        } else {
            JOptionPane.showMessageDialog(null, "Por favor seleccione una tienda");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * Metodo para llenar la tabla con las tiendas existentes
     * @param args the command line arguments
     */
    public void llenarTabla(JTextField filtro, String accion, boolean cliente, JTable tabla, String value, String tienda) {
        String campo = filtro.getText();
        String where = "";
        
        where = "WHERE " + value + " LIKE '%" + campo + "%' || nombre LIKE '%" + campo + "%' ORDER BY nombre ASC";
        try {
            DefaultTableModel model = new DefaultTableModel() {
                @Override
                public boolean isCellEditable(int row, int column) {
                    return false;
                }
            };
            tabla.setModel(model);
            String query = accion + where + tienda;
            ResultSet Result = Main.conexion.ComboBox(query);
            ResultSetMetaData rsMd = Result.getMetaData();
            int cantidadColumnas = rsMd.getColumnCount();
            model.addColumn("Codigo");
            model.addColumn("Nombre");
            model.addColumn("Direccion");
            model.addColumn("Telefono");
            model.addColumn("Telefono 2");
            model.addColumn("Correo");
            model.addColumn("Horario");
            while (Result.next()) {
                Object[] filas = new Object[cantidadColumnas];
                for (int i = 0; i < cantidadColumnas; i++) {
                    filas[i] = Result.getObject(i + 1);
                }
                model.addRow(filas);
            }
        } catch (SQLException e) {
            System.out.println(e.toString());
        }
    }
    /**
     * Keylistener para filtrar las tiendas por codigo
     */
    public void Keilstener() {
        codigotxt.getDocument().addDocumentListener(new DocumentListener() {
            @Override
            public void insertUpdate(DocumentEvent de) {
                llenarTabla(codigotxt, "SELECT codigo, nombre, direccion, telefono1, telefono2, correo, horario FROM TIENDA ", true, tiendatable, "codigo", "");
            }
            
            @Override
            public void removeUpdate(DocumentEvent de) {
                llenarTabla(codigotxt, "SELECT codigo, nombre, direccion, telefono1, telefono2, correo, horario FROM TIENDA ", true, tiendatable, "codigo", "");
            }
            
            @Override
            public void changedUpdate(DocumentEvent de) {
                llenarTabla(codigotxt, "SELECT codigo, nombre, direccion, telefono1, telefono2, correo, horario FROM TIENDA ", true, tiendatable, "codigo", "");
            }
        });
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VisualizarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VisualizarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VisualizarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VisualizarTienda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VisualizarTienda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField codigotexto;
    private javax.swing.JTextField codigotxt;
    private javax.swing.JTextField correo2;
    private javax.swing.JTextField direccion;
    private javax.swing.JTextField horario;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField nombre;
    private javax.swing.JTextField telefono;
    private javax.swing.JTextField telefono2;
    private javax.swing.JTable tiendatable;
    // End of variables declaration//GEN-END:variables
}
